export enum BookActionTypes {
    SET_BOOK = 'SET_BOOK',
    GET_BOOKS_REQUEST = 'GET_BOOKS_REQUEST',
    GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS',
    GET_BOOKS_FAILURE = 'GET_BOOKS_FAILURE',
    CLEAR_BOOKS = 'CLEAR_BOOKS'
}